import { Router } from "express";
import { grRouter } from "./gr.route";
import { unitRouter } from "./unit.route";
import { productRouter } from "./product.route";
import { inventoryRouter } from "./inventory.route";
import { installationRouter } from "./installation.route";
import { qrRouter } from "./qr.route";
import { logRouter } from "./log.route";
import { authCheck } from "@src/middleware/auth.middleware";
import { hasPermission } from "@middlewares/permission.middleware";
import { bulkInstallationRouter } from "./bulk-installation.route";
export const grRoute = Router();
grRoute.use(authCheck);
grRoute.use(grRouter);
grRoute.use("/units", hasPermission("gr-module"), unitRouter);
grRoute.use("/products",hasPermission("gr-module"),  productRouter);
grRoute.use("/inventory", inventoryRouter);
grRoute.use("/installations", installationRouter);
grRoute.use("/qr", qrRouter);
grRoute.use("/logs", logRouter);
grRoute.use("/bulk-installation", bulkInstallationRouter);